# Generated by Django 5.1.2 on 2025-01-08 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.CharField(max_length=10)),
                ('jumlah_kursi', models.IntegerField()),
                ('status_meja', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipesan', 'Dipesan'), ('digunakan', 'Digunakan')], max_length=20)),
                ('lokasi', models.CharField(max_length=100)),
                ('jenis_meja', models.CharField(choices=[('reguler', 'Reguler'), ('VIP', 'VIP'), ('outdoor', 'Outdoor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_reservasi', models.DateField()),
                ('waktu_reservasi', models.TimeField()),
                ('jumlah_orang', models.IntegerField()),
                ('status_reservasi', models.CharField(choices=[('Diterima', 'Diterima'), ('Dibatalkan', 'Dibatalkan'), ('Selesai', 'Selesai'), ('Ditunda', 'Ditunda')], max_length=20)),
                ('meja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.meja')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(choices=[('Kartu Kredit', 'Kartu Kredit'), ('Tunai', 'Tunai'), ('Transfer Bank', 'Transfer Bank')], max_length=20)),
                ('status_pembayaran', models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Dibayar', 'Dibayar'), ('Gagal', 'Gagal')], max_length=20)),
                ('reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.reservasi')),
            ],
        ),
    ]
