# Generated by Django 5.1.2 on 2025-01-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meja',
            options={'verbose_name': 'Meja', 'verbose_name_plural': 'Meja'},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name': 'Pelanggan', 'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'verbose_name': 'Pembayaran', 'verbose_name_plural': 'Pembayaran'},
        ),
        migrations.AlterModelOptions(
            name='reservasi',
            options={'verbose_name': 'Reservasi', 'verbose_name_plural': 'Reservasi'},
        ),
        migrations.RemoveField(
            model_name='meja',
            name='lokasi',
        ),
    ]
